### ISSUE TITLE
Version 1.2 Issues

### ISSUE THREAD

**Issue by LoganSutherland** [Duskkiller/Dal-Robotics#1]
Right now the Thyimo will follow the line just fine, and will begin the turn sequence.  But when it starts the curve it just has a major fucking seizure and bugs out.  I think its a problem with recognizing the state it's in, or maybe its reverting to NORMAL.  Anyway I'm gonna work on it over the next few days but if anyone wants to take a crack at it feel free.

PS. The turning system I added is just provisional right now.  It's just in case we can't come up with something better before the due date.  After we fix this bug it should be fully functional.  I'll be working on modifying it to the intended turning model this weekend.

**Comment by liamhebert** [comment]
I'll take a crack at this late friday night if we don't fix it before then
